name: Build and Package Api project

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'retrotrack.web/**'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.3.0

    - name: Build Docker Image
      run: |
        docker build -t retrotrackapi -f RetroTrack/RetroTrack/Dockerfile .
        
    - name: Save Docker Image
      run: |
        docker save retrotrackapi > retrotrackapi.tar

    - name: Upload Docker Image
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        source: retrotrackapi.tar
        target: ${{ secrets.TARGET }}
        
    - name: Stop And Remove Current Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
            docker stop retrotrackapi || true && docker rm retrotrackapi || true
    - name: Load New Docker Image
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker load -i ${{ secrets.TARGET }}retrotrackapi.tar

    - name: Start New Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker run -d -p 5003:8080 --mount type=bind,source="${{ secrets.FILE_PATH }}",target=/app/Logs --env RetroTrackConnString='${{ secrets.ENV }}' --name retrotrackapi retrotrackapi:latest

    - name: Clean Up The Tar File
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          rm ${{ secrets.TARGET }}retrotrackapi.tar