name: Build and Package Website

on:
  push:
    branches:
      - 'master'
    paths:
      - 'retrotrack.web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.3.0

    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1.3.0
      with:
        envkey_API_URL: ${{ secrets.API_URL }}
        envkey_NEXT_PUBLIC_WEB_URL: "https://retrotrack.bregan.me"
        envkey_API_SECRET: ${{ secrets.API_SECRET }}
        directory: retrotrack.web/
        file_name: .env.production
        fail_on_empty: false

    - name: Build Docker Image
      run: |
        cd retrotrack.web/
        docker build -t retrotrackwebsite .
        
    - name: Save Docker Image
      run: |
        docker save retrotrackwebsite > retrotrackwebsite.tar

    - name: Upload Docker Image
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        source: retrotrackwebsite.tar
        target: ${{ secrets.TARGET }}
        
    - name: Stop And Remove Current Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
            docker stop retrotrackwebsite || true && docker rm retrotrackwebsite || true
    - name: Load New Docker Image
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker load -i ${{ secrets.TARGET }}retrotrackwebsite.tar

    - name: Start New Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker run -d -p 3001:3000 --name retrotrackwebsite retrotrackwebsite:latest

    - name: Clean Up The Tar File
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          rm ${{ secrets.TARGET }}retrotrackwebsite.tar