name: ESLint on PR

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci
        working-directory: retrotrack.web

      - name: Run ESLint
        run: npx eslint . --config eslint.config.mjs
        working-directory: retrotrack.web
